In [1]:
from torch import nn
from mlip.pes import PotentialNeuralNet
from mlip.reann import REANN, compress_symbols

species = [29]

device = 'cpu'

lmax = 2
nmax = 10
loop = 3

encode, decode, numbers = compress_symbols(species)
species = list(set(numbers))
reann = REANN(species, nmax=nmax, lmax=lmax, loop=loop)

moduledict = nn.ModuleDict()
desc = reann
for spe in species:
    moduledict[str(spe)] = nn.Sequential(
        nn.Linear(desc.NO, int(desc.NO*1.3)),
        nn.SiLU(),
        nn.Linear(int(desc.NO*1.3), 1)
    )
moduledict = moduledict.double().to(device=device)
    
model = PotentialNeuralNet(desc, moduledict, species)


/home/schinavro/anaconda3/envs/simple/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


# Load data

In [2]:
import numpy as np
from pymatgen.core import Structure
from monty.serialization import loadfn
location = "../data/Cu/"
data = loadfn(location + 'training.json')

#data[0]['structure'].cart_coords;
#data[0]['structure'].lattice.matrix;
#data[0]['outputs']['forces'];
#data[0]['structure'].lattice.pbc;
#data[0]['num_atoms']

symbols = [[encode[n] for n in d['structure'].atomic_numbers] for d in data]
positions = [d['structure'].cart_coords for d in data]
energies = [d['outputs']['energy'] for d in data]
cells = [d['structure'].lattice.matrix for d in data]
gradients = [-np.array(d['outputs']['forces']) for d in data]

crystalidx = [[idx] * data[idx]['num_atoms'] for idx in range(len(data))]
pbcs = [np.array(d['structure'].lattice.pbc) for d in data]
           

In [3]:
# Nomenclature
# SPECG-CriP(symbols, positions, energies, cells, gradients, crystalindex, pbcs)

import torch as tc
from torch.utils.data import Dataset, DataLoader

class BPTypeDataset(Dataset):
    
    """Behler Parrinello Type datasets
    Indexing should be done in the unit of crystal, a set of atom used in one calculation. 
    
    
    Parameters
    ----------
        symbols: List
        positions: List
        energies: List
        cells: List
    
    
    """
    def __init__(self, symbols, positions, energies, cells, gradients, crystalidx, pbcs):
        self.symbols = symbols
        self.positions = positions
        self.energies = energies
        self.cells = cells
        self.gradients = gradients
        self.crystalidx = crystalidx
        self.pbcs = pbcs

    def __len__(self):
        return len(self.energies)
    
    def __getitem__(self, idx):
        return self.symbols[idx], self.positions[idx], self.energies[idx], self.cells[idx], self.gradients[idx], self.crystalidx[idx], self.pbcs[idx]

    
def concate(batch, device='cpu'):
    cat = lambda x: tc.from_numpy(np.concatenate(x))
    
    symbols, positions, energies, cells, gradients, crystalidx, pbcs = [], [], [], [], [], [], []
    for data in batch:
        symbol, position, energy, cell, gradient, crystali, pbc = data
        symbols.append(symbol)
        positions.append(position)
        energies.append(energy)
        cells.append(cell[None])
        gradients.append(gradient)
        crystalidx.append(crystali)
        pbcs.append(pbc[None])      

    return (cat(symbols), cat(positions).to(device=device).requires_grad_(True), 
            energies, cat(cells).to(device=device).requires_grad_(True), 
            cat(gradients), cat(crystalidx), cat(pbcs))

imgdataset = BPTypeDataset(symbols, positions, energies, cells, gradients, crystalidx, pbcs)
dataloader = DataLoader(imgdataset, batch_size=10, shuffle=True, collate_fn=concate)


In [14]:
class MSEFLoss:
    def __call__(self, predE, predF, y, dy):
        N = len(y)
        A = len(dy)
        self.lossE = tc.sum((y - predE) ** 2) / N
        self.lossG = tc.sum((predF - dy)**2) / A
        return self.lossE + self.lossG


class Normalizer(object):
    """Normalize a Tensor and restore it later. """

    def __init__(self, tensor, device='cpu'):
        """tensor is taken as a sample to calculate the mean and std"""
        self.mean = tc.mean(tensor).to(device=device)
        self.std = tc.std(tensor).to(device=device)

    def norm(self, tensor):
        return (tensor - self.mean) / self.std

    def denorm(self, normed_tensor):
        return normed_tensor * self.std + self.mean

    def state_dict(self):
        return {'mean': self.mean,
                'std': self.std}

    def load_state_dict(self, state_dict):
        self.mean = state_dict['mean']
        self.std = state_dict['std']

In [ ]:
import torch as tc
from torch.autograd import grad

def train(dataloader, model, loss_fn, optimizer, normalizer, device='cpu'):
    model.train()
    for batch, _ in enumerate(dataloader):

        symbols, positions, energies, cells, gradients, crystalidx, pbcs = _
        
        # Backpropagation
        optimizer.zero_grad()

        _, pred, predG = model(symbols, positions, cells, crystalidx, pbcs)
        
        loss = loss_fn(pred, predG, normalizer.norm(tc.tensor(energies)), gradients)
        
        loss.requires_grad_(True)
        
        loss.backward()
        print(model.desc.α.grad)
        optimizer.step()
        print(loss)

    return loss_fn.lossE, loss_fn.lossG

from torch.utils.tensorboard import SummaryWriter
writer = SummaryWriter(log_dir='./20220727/copper_log')

normalizer = Normalizer(tc.tensor(imgdataset.energies).double())

for t in range(5000):
    lossE, lossG = train(dataloader, model, MSEFLoss(), 
                         tc.optim.Adam(model.parameters(), lr=1e-2), normalizer)

    writer.add_scalar('Loss / MSE energy (eV)', lossE, t)
    writer.add_scalar('Loss / MSE grad (eV/A)', lossG, t)
    if t % 10 == 0:
        tc.save(model.state_dict(), './20220727/weights2_%d.pt' % t)

writer.flush()
writer.close()

tensor([[ -131.5893,  -185.0634,  -609.3994,  2372.9529, -3006.9062,  4890.5400,
         -1542.9200,  -483.6465,  5620.0674,   235.9423]])
tensor(6474.4111, dtype=torch.float64, grad_fn=<AddBackward0>)
tensor([[  29.0423, -455.2028, -229.9046,  432.2812, -962.9335, 1033.6934,
         -309.9249, -201.7359,  180.8158,  121.3441]])
tensor(3551.4508, dtype=torch.float64, grad_fn=<AddBackward0>)
tensor([[  -16.4997,  -463.4565,  -145.4250,   193.0038,  -546.4291,   387.7461,
          -744.3372,  -156.9509, -1191.2640,    89.7487]])
tensor(2693.5206, dtype=torch.float64, grad_fn=<AddBackward0>)
tensor([[  67.9666, -750.5685,    1.0126,   53.3926, -304.9118,    6.0345,
          577.2721,  -29.3815, -368.6872,   44.7145]])
tensor(2077.0459, dtype=torch.float64, grad_fn=<AddBackward0>)
tensor([[ 8.6188e+18, -1.0924e+19,  1.9780e+18,  1.1382e+17, -5.1406e+17,
          4.7780e+18,  5.1057e+19,  4.7258e+18,  3.0867e+19,  2.4055e+18]])
tensor(2.8715e+18, dtype=torch.float64, grad_fn=<AddBackwa

In [11]:
model.desc.α.grad

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])